import os
import logging

logger = logging.getLogger("multicliswarm.docs_engine")

def generate_docs(project_dir: str, language: str):
    """
    Auto-generates documentation for the project.
    """
    logger.info(f"Generating documentation for {language} project...")
    
    docs_path = os.path.join(project_dir, "docs")
    os.makedirs(docs_path, exist_ok=True)
    
    # MkDocs setup
    mkdocs_yaml = f"""
site_name: MultiCliSwarm Generated Docs
theme: readthedocs
nav:
  - Home: index.md
"""
    with open(os.path.join(project_dir, "mkdocs.yml"), "w") as f:
        f.write(mkdocs_yaml.strip())
        
    index_md = f"""
# Project Documentation
This documentation was automatically generated by **MultiCliSwarm**.

## Project Overview
Language: {language}
Generated Files:
"""
    # List files
    for root, _, files in os.walk(project_dir):
        for f in files:
            if f.endswith(('.py', '.js', '.ts', '.go')):
                index_md += f"- {os.path.relpath(os.path.join(root, f), project_dir)}\n"
                
    with open(os.path.join(docs_path, "index.md"), "w") as f:
        f.write(index_md.strip())
        
    logger.info("MkDocs structure generated.")
